#!/bin/zsh
#
# Makes sure development environment is setup

if ! which android > /dev/null; then
  echo 'Please install android sdk' >&2
  exit 1
fi

if ! which cordova > /dev/null; then
  echo 'Installing Cordova' >&2
  npm install -g cordova
fi

cordova platform add android

exit 0
